### ISSUE TITLE
Set up GPG keys for whole team and start make verified commits 

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#106]

**Comment by asadovka** [comment]
we can quickly process it via keybase pgp generator tool

**Comment by asadovka** [comment]
I've already generated them for my account

**Comment by SaveTheAles** [comment]
Signed commits have:
- [ ] @litvintech 
- [ ] @asadovka 
- [ ] @xhipster 
- [ ] @hleb-albau 
- [ ] @arturalbov 
- [ ] @vstavetski 
- [ ] @Pechalka 
- [ ] @Olga584 
- [ ] @SaveTheAles

**Comment by SaveTheAles** [comment]
Bad news for gitkraken users 
![image](https://user-images.githubusercontent.com/36516972/46198150-71c07280-c314-11e8-988e-ac02b9ad65a6.png)

**Comment by asadovka** [comment]
@xhipster @hleb-albau @vstavetski @Pechalka @Olga584 please, follow the instructions)

**Comment by asadovka** [comment]
added cyberadmin

**Comment by vstavetski** [comment]
If you get an error when creating a commit then try this:
https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html

**Comment by asadovka** [comment]
@xhipster waiting for you

**Comment by xhipster** [comment]
Tried several times. Just don't work for me... Every time different errors. GPG is, in fact, outdated technology. It's better to invest the time in [more radical](https://github.com/radicle-dev/radicle) stuff

<img width="732" alt="Screen Shot 2019-03-13 at 17 34 45" src="https://user-images.githubusercontent.com/410789/54272498-686f4d80-45b6-11e9-83f9-3d1917f6dd86.png">
