### ISSUE TITLE
Automate tokenflow

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#108]
1. Set up Aragon organization (?)
2. Automate congress' tokenflow
3. Actualize balances

**Comment by asadovka** [comment]
@xhipster sure, we have some ideas on [that](https://github.com/Giveth/planning-app)

**Comment by xhipster** [comment]
What about [that](https://docs.colony.io/colonynetwork/docs-colony/)? And [this](https://colony.io/whitepaper.pdf)? Really well thought thing!

**Comment by asadovka** [comment]
balances are actualized in OOS

**Comment by asadovka** [comment]
we've researched and discussed this topic and decided to stay on OOS docs. Aragon orgs and Giveth are currently raw for governance.
