### ISSUE TITLE
Update roadmap for MVP

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#11]
We need to define epics, dependencies between them and put them on the [cyber•Search product roadmap](https://github.com/orgs/cybercongress/projects/1)

**Comment by litvintech** [comment]
convert our mindmap to drafted linked roadmap with feature descriptions, splitted with sprints
for example: [cosmos roadmap](https://cosmos.network/roadmap)

**Comment by asadovka** [comment]
Chaingear initial roadmap (7 sprint):
https://github.com/cybercongress/chaingear/wiki/Roadmap

**Comment by 21xhipster** [comment]
@asadovka Why the scope is only two projects?

**Comment by 21xhipster** [comment]
@asadovka Sorry. I I kill your plan in issue description and put there mine. It is more top-down approach, not down-top. Hope that help.

**Comment by asadovka** [comment]
https://www.mindmeister.com/1117319175?t=EarAM9OH3d#
