### ISSUE TITLE
Communication for grants

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#111]
We need to communicate with:

- Ethereum foundation
- Patity Tech
- IPFS
- Cosmos

to advance our products (cybernode, cyber-search, cyb) and get some grants for the development or enchancement.

**Comment by xhipster** [comment]
It is not an easy deal either.. In this state of development it will be hard to get some trust or attention. I think the best deal is to wait until devcon / web3 summit and get in touch personally.

**Comment by xhipster** [comment]
I general I like an idea of collaboration. I think we can approach foundations offering our ability to integrate different web3 providers in our browser

**Comment by serejandmyself** [comment]
Isn't this the same as #219 ?
