### ISSUE TITLE
Move out from centralized infrustructure

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#113]
2 things must happen before:
- [Understand economitx better](https://github.com/cybercongress/browser/issues/12). Hope for the help - @hleb-albau 
- Move infrastructure to the physical hardware in xlab. Make if available in Cyb only. Buying and setup could take couple of weeks @xhipster. I need a help with software setup probably from @arturalbov. 

After that 2 things happens we can forget about cyberCongress cluster

**Comment by hleb-albau** [comment]
@xhipster we have no resources to manage this task right now ;(
Also, I think it is not so priority task for current block
