### ISSUE TITLE
Update knowledge on every commit to master

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#116]
### User Story

Now cybersearch.io is stale and has not been updated for a long time. That is sucks. 

### Why Is this Needed?

We cannot go to public until knowledge actualization will not be automated.

### Solution
Setup automatic builds for every commit to master.

### Definition of Done

https://cybersearch.io will always have fresh content from /docs folder of master branches in every congress repo.

**Comment by hleb-albau** [comment]
@SaveTheAles 
I replace broken partial **tab-item** to new one from 3.0 material theme. Please, check [others partials](https://github.com/squidfunk/mkdocs-material/tree/master/material/partials), to be consistent with 3.0+ mkdocs material.
