### ISSUE TITLE
Fix markup of wiki.cybercongress.ai

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#121]
### Current Behavior
Page margins was cut out of original Material MkDocs. 
Right column with contents and logo also disappeared.
We need to turn them back as information at wiki is unreadable.

Compare the difference:
Without margins (unreadable):
<img width="1671" alt="screen shot 2018-09-29 at 14 13 21" src="https://user-images.githubusercontent.com/410789/46245141-e7e6d700-c3f1-11e8-9506-30e062e3ec32.png">
With margins (readable)
<img width="1680" alt="screen shot 2018-09-29 at 14 13 43" src="https://user-images.githubusercontent.com/410789/46245143-eb7a5e00-c3f1-11e8-9e95-798c71a2529f.png">

### Expected Behavior
Must follow original Material MkDocs.

### Definition of Done
Must be readable

**Comment by SaveTheAles** [comment]
+
- [ ] favicon bug
- [ ] hamburger menu is not working

**Comment by SaveTheAles** [comment]
done

available at https://wiki.cybercongress.ai/

- fix favicon
- fix hamburger menu
- now readable
- add right-side menu
