### ISSUE TITLE
State of cyberd post

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#127]
According to [plan](https://github.com/cybercongress/congress/blob/master/blog/roadmap.md) it should post at 2018/10/10

**Comment by xhipster** [comment]
![image 2019-01-25 01 15 47](https://user-images.githubusercontent.com/410789/51714697-bf3cba00-203e-11e9-84b1-cd89a3846183.jpg)

We have something to say

**Comment by xhipster** [comment]
<img width="1043" alt="screenshot 2019-01-25 at 01 16 16" src="https://user-images.githubusercontent.com/410789/51714736-e4312d00-203e-11e9-80b9-22361f505c2d.png">

**Comment by SaveTheAles** [comment]
@hleb-albau has already good intro for this post

https://hleb-albau.com/your-chain-genesis-based-on-ethereum-network-activity

@xhipster what do you think?

**Comment by xhipster** [comment]
@hleb-albau I somehow missed. The post is great, but not about state of cyberd. I think I will close this issue due to a lot of reasons.

btw: @hleb-albau Subscribed to your blog
