### ISSUE TITLE
Cyber merch for devcon

### ISSUE THREAD

**Issue by cyberadmin** [cybercongress/congress#129]
- t-shirts
- prints
- magnets
- stickers

we develop fun and some sarcastic things. but we keep distance from religion and politics!

**Comment by asadovka** [comment]
Browser t-shirt ideas
1. Packman style (cyb eats chrome, opera, edge)
2. "Got web3?" - "cyb!" or cyb on the back (allusion on "got milk?")
3. Art of browser logo + name + QR (back)
4. web3 is coming (allusion of Game of Thrones)
5. Ready for web3? + cyb logo

**Comment by asadovka** [comment]
Issue moved to [cybercongress/cyberdesign #1](https://github.com/cybercongress/cyberdesign/issues/1) via [**ZenHub**](https://www.zenhub.com/)
