### ISSUE TITLE
Migrate wiki

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#138]
- Create a separate repo for wiki.congress. 
- Migrate current gh-pages to this repo
- Add landing to congress' gh pages branch

**Comment by SaveTheAles** [comment]
@asadovka 
@xhipster proposal to do not create separate repo and migrate wiki to library

**Comment by asadovka** [comment]
@SaveTheAles nice idea!

**Comment by asadovka** [comment]
landing was added https://cybercongress.github.io/congress/
