### ISSUE TITLE
Create cyberd-wiki-index repository

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/congress#155]
I want to create a dedicated repo for a standalone app cyberd wiki index.
It will be supplied via docker image. Provide next functionality:

* populate cyberd with wiki index
* serve duri via ipfs

@xhipster @litvintech

**Comment by hleb-albau** [comment]
Still actual......

**Comment by litvintech** [comment]
accepting

**Comment by asadovka** [comment]
@asadovka test

**Comment by xhipster** [comment]
accepting. Already considered in cyb/docs/cyb.md

**Comment by hleb-albau** [comment]
@xhipster It will be maintained by me. Releases will be mostly separate from cyberd. If the protocol changed, then a new major release will be applied to wiki-index.
