### ISSUE TITLE
@dimakorzhovnik - new team member

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#156]
Proposal to include [Dima](https://github.com/dimakorzhovnik) to cybercongress team as a makeup man. Perspectives: frontend development. 

His work you can check [here](https://github.com/cybercongress/ui.cyb)

**Comment by xhipster** [comment]
After short hangout we decide to meet in a week with a goal to discuss important terms of collaboration:

Dima will suggest really cool front end projects which amazed him and we will discuss them. It is important to synchronize our vision on what kind of frontend we expect to deliver from him.

Also, a gave a link to different values which are important for us:

1. Compliance with [cyberCongress](https://cybercongress.ai) values. Readiness to switch to ETH & BTC from USD & BYN.
2. Understanding web3. Readiness to dedicate a passion to the p2p technologies such as ethereum and ipfs.
3. Understanding the differences between open source and proprietary culture. Readiness to follow open source culture.

Also, an important question is the readiness to work with a team offshore. Will he go to Thailand?

**Comment by xhipster** [comment]
Accepted

**Comment by hleb-albau** [comment]
Accepted

**Comment by asadovka** [comment]
[done](https://github.com/cybercongress/congress/blob/master/teams/cybersearch.toml)
