### ISSUE TITLE
Define communication process

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/congress#161]

**Comment by hleb-albau** [comment]
@xhipster Please, add more description. Not oblivious, what you want to archive here.

**Comment by serejandmyself** [comment]
Create 3 types of event

**Comment by serejandmyself** [comment]
@xhipster please see initial proposal:

https://github.com/cybercongress/congress/blob/master/blog/proposal.md

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/blob/master/teams/communication%20and%20publishing.md

**Comment by serejandmyself** [comment]
@xhipster

**Comment by xhipster** [comment]
After long discussion with @serejandmyself [something that could work as foundation](https://github.com/orgs/cybercongress/projects/2) has been born. The next steps are:
- [ ] more formalization in [this](https://github.com/cybercongress/congress/blob/master/teams/communication%20and%20publishing.md) document
- [ ] spread the idea in the team
- [ ] gather story points from the team

**Comment by mastercyb** [comment]
Bot relevant
