### ISSUE TITLE
cyber-markets & cyber-search

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#163]
# Rationale

We don't need parser of untrusted sources such as centralized exchanges. We just can not rely on their information. We need to redo this project with parsing trades directly from blockchain transactions in mind.

What do you think? @vstavetski @hleb-albau @arturalbov 

# Expected steps

1. Movement of useful code and issues into cyber-search
2. Archiving this repo as a standalone project.

Implementation of actual functionality can be pushed by a community

Now I think @hleb-albau was right 💯

**Comment by hleb-albau** [comment]
@xhipster 
I agreed that we don't need a parser for cexes. 
But, markets and search are different in their goals and should not share the same infrastructure. Most of the logic from here is not about how to get data, but rather how to process, store and provide it.

I would suggest to just archive them both, keeping as is. Also, move all cluster definitions from cybernode repo to search\market and close cybernode repo and dockerhub too.

**Comment by xhipster** [comment]
As I understand correctly your @hleb-albau suggestion is to stop development of scripts inside of Congress that will help us to populate cyberd index?

**Comment by hleb-albau** [comment]
For the current moment yes.

**Comment by xhipster** [comment]
Agreed

**Comment by xhipster** [comment]
@hleb-albau Please kill them yourself :-) It is your babies

**Comment by asadovka** [comment]
Seems that no one came to a single solution. Let's archive these repos for a while.
