### ISSUE TITLE
Cyb repos

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#164]
There will be a new list of cyb repos:
1. cyb - cyb shell & .cyb app itself
2. cyb-ui - storybook for cyb
4. app.search - frontend for cyberd-search app

- .help will be merged with Cyb repo.
- cyb cli - no current agreement. leave as is
- app.ipfs and app.wiki - no current agreement
- .eth and .cbd will be currently in cyb
- chaingear frontend will be in chaingear repo

**Comment by xhipster** [comment]
# Updated Version of Proposal

This repos must be standalone:
- cyb - cyb shell & .cyb app itself
- ui.cyb - storybook for cyb
- .eth - frontend for eth explorer
- .dev - dev  tools for app development
- .wiki - static wikipedia in ipfs
- .ipfs - ipfs frontend for cyb
- .chaingear - frontend for chaingear.
- .cyber - frontend for cyber protocol.

To merge into Cyb:
- .help  - must be an essential function of cyb, hence it must be moved to help.cyb
- cyb-cli - cli functionality must be essential of browser's core and all things ui must be developed on top of the cli.

Principally against diferrentiation between .cyber and .search. It is a big mistake in the industry to differentiate explorer with app functionality. Any app require transactions and contracts. That is why all blockchain apps are so ugly. Do not want to become the part of this pitty group of early web3 apps. Our case is an app specific blockhain. Hence we will impement explorer functionaly as essential part of an app with reuse of elements in mind.

**Comment by asadovka** [comment]
@xhipster,I think better option is to communicate live

**Comment by asadovka** [comment]
.help is now ready to be removed from cyber.Congress

**Comment by xhipster** [comment]
Cool!

**Comment by serejandmyself** [comment]
Seems completely irrelevant
