### ISSUE TITLE
Cyber glossary

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#165]
### Rationale

Seems that we all came to the point where no one of our team can easily distinguish project names, repos, tokens, and all that .cyber. stuff 

### Solution

1. A live conversation about project statuses, naming etc.
2. Recorded results of conversation in .md file

### Implementation

A simple .md file in  Congress repo where everyone can easily get into cyber theme.

**Comment by xhipster** [comment]
cyb:
- nick. a friendly software robot who helps you explore universes

cyber:
- noun. a superintelligent network computer for answers
- verb. to do something intelligent, to be very smart

cyber://
- web3 protocol for computing answers and knowledge exchange

CYB:
- ticker. transferable token expressing a will to become smarter

CYBER:
- ticker. non-transferable token measuring intelligence

CBD:
- ticker. ERC-20 proto token representing substance from which CYB emerge

cyberlink:
- link type. expressing connection from one link to another as link-x.link-y

Also it is in the header of [the paper](https://github.com/cybercongress/cyberd/blob/master/docs/cyberd.md)

**Comment by asadovka** [comment]
@xhipsterI've seen it.
the task is actually much wider than just some terms from cyberd.dm 

for example:

what is chaingear, congress, cyber.Search, cyb as a browser, cybernode etc.

**Comment by xhipster** [comment]
Okey! Let us gather in this thread all terms that need definitions.

**Comment by serejandmyself** [comment]
Are there any docs that anyone had managed to gather with the required info? 

I'd happily take this on

**Comment by serejandmyself** [comment]
@xhipster ?

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/issues/290
