### ISSUE TITLE
Release management optimization

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#166]
### Rationale

We have sprints and blocks - it is a time-based segmentation of the working process. We also need a clear vision for tasks, that should be in major releases. Now we use [GitHub projects](https://github.com/orgs/cybercongress/projects) and [ZenHub releases](https://github.com/cybercongress/cyb#workspaces/congress-5a72d6edd43dfe311271511e/reports?report=release&release=5adb6e6d9c8b9c43c2b77bbf) for planning, but nobody really cares.

My proposal is to use only GitHub project as a release board (similar as a sprint board)
1. there will be a separate project for each release
2. each project consists of epics (maybe some important issues)
3. epics are placed in columns - done, in progress, enhancements etc.
 
We can use separate projects for each repo as well - let's discuss it!

Thus, everyone can see our progress on work (Zenhub releases are worked only for logined users)

Some cool examples:

https://github.com/github/hub/projects/1
https://github.com/ethereum/go-ethereum/projects/15

### Solution

Common project on GitHub or separate projects for each repo

**Comment by asadovka** [comment]
also, I think it's time to stop using cyber.search as a project name. now projects can be named according to release names

**Comment by asadovka** [comment]
me and @litvintech are currently testing projects

**Comment by xhipster** [comment]
My proposal is to cut points measurement and remove zenhub from workflow

**Comment by asadovka** [comment]
@xhipster https://help.github.com/articles/viewing-your-milestone-s-progress/

**Comment by asadovka** [comment]
https://medium.com/the-andela-way/how-to-build-a-power-up-for-your-github-project-board-for-project-management-344d5b380a68

**Comment by asadovka** [comment]
Current solution:

1. Planning for releases (not sprints) 
2. Minor release - every week. Major - critical mass of minor releases.
3. Planning is processed once a week (monday) demo&retro - friday, same week

4. Remove zenhub. All functions and metrics can be found in native github
5. Use organisation projects for all products major releases (0.2, 0.3 etc.). Projects consists of epics (cards with refferenced issues)
6. Use repo's projects for minor releases (0.2.1, 0.2.2 etc.). Projects consist of simple issues

**Comment by asadovka** [comment]
issue:
1. good description with task list 
2. one assigne
3. labels
4. refferenced commits/PR's

Epic:
- group of issues by common theme and problem
- implementation - card in Organisation progect with refferences issues

**Comment by xhipster** [comment]
Awesome, I would love to try the new scheme. 
I see the following benefits:
- Native github tooling is faster and more confident personally for me.
- Less admin work for sprint accounting which is not so useful either
- Issue accounting and planning are focused now on releases (particular results) not the end of sprint. I hope we got a better overall quality of software releases.
- Faster, small iterations without the bloat of tasks
- Using only projects for planning, we will have one beautiful source of truth for delivery which is the most important. Now we don't have the one.

We need opinion from @hleb-albau and @litvintech and probably broader @cybercongress/cyb and @cybercongress/cyber teams

**Comment by asadovka** [comment]
@xhipster also the benefit of using native Github functions is that every Github user can see our progress and plans.

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/projects/2

**Comment by asadovka** [comment]
https://github.com/orgs/cybercongress/projects

**Comment by xhipster** [comment]
I think its done
