### ISSUE TITLE
Belchikov Anatoli - new member of cybercongress team

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#167]
### Rationale

Anatoli currently is working with us (part-time). We need to agree on his team status, projects occupation and etc.

### Solution

Conversation for clarifying the vision of Anatoli as a team member.

**Comment by xhipster** [comment]
Part-timers can be in the team easily but only if they work with us long term, for the time being.
1. We need to ask @belya does that correct or not?
2. We need to align it with @Snedashkovsky. I am not sure that this are the terms that were initially agreed

**Comment by hleb-albau** [comment]
Seems we miss Anatoly. Our last work contact was on our launch,3jan.

**Comment by belya** [comment]
@xhipster Ok! I understand, no problem with that. I'll read the project documentation carefully and will try to buidl something useful for cybercongress to become a full team member.
