### ISSUE TITLE
Chaingear beneficiaries

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#169]
So, all operational functions of Chaingear are currently processed by cyberCongress multisig account.

But there is also an option for beneficiaries, addresses which will achieve profit from Chaingear's fees. We should discuss it and come to a consensus of address list with the whole team.

**Comment by litvintech** [comment]
We discussed with @xhipster that for now there is only one good option - congress multisig as beneficiary, for 0.2 we will add chaingear community fund as second one

**Comment by litvintech** [comment]
Chaingear deployed with congress multisig as just one beneficiary
