### ISSUE TITLE
Notes to the distribution note

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#177]
- There is a proposition of experementing with 3 netwrok swarms. Why not add Fund Request? It is open-source, ETH based and has already seen some traction from Aragon, Vechain and a few more. After all, I believe that all projects, small and big should have an equal opportunity and chance to contribute.

They also have the Arkane network, which in theory, could serve as some kind of another cool feature for the ERC-20 based tokens

- I have been planning to write a paper on token distribution (study and a proposition for a more equal distribution) for a while. Your note got me thinking and reminded me of that:
https://github.com/serejandmyself/Work-Management/issues/54

I have an open issue, that I will be trying to complete over the next months or so. So (1) if you can think of any pointers for me, I will be grateful, just drop them in the issue. (2) In the comment, I have tried to list some of the ways how tokens can be distributed. This means that the ways you propose aren't complete. For example: there can be a claim during a bounty, that shows the need of the tokens to the distributed addresses (a simple signature would be required). This will both - cross out complete noobs that are silly enough not to be able to sign a message or to google it (pun intended) and cross out "sleeping addresses" that are lost / etc

This is just an example. I have in the comments already mentioned some other ways. Maybe you can find some of them of use.

**Comment by hleb-albau** [comment]
"\

> One small add on:
> 
> I have noticed that after time validators start to have a lions share of the network, as important as they are to the network (no argument here) - do you not see rather an ironic twist?
> 
> You are fighting one of the main "enemies" - Alphabet (google). It is a company with so much power that in a philosophical term. one can say is currently responsible for validating our search and searching for transactions on the www.
> 
> Problems arise when rebels don't take off their beret after the revolution. Google is a great example of once a rebel, that after it won the revolution, forgot to take its beret off (parallel to Saddam Hussein, Idi Amin etc). Are you not afraid that you might end up with the same issue as per allocating so much power essentially to the validators (we can see scenarios evolving in some existing networks already where validators have way to much political power).
> 
> IMO by allocating them such a huge proportion of the distribution (even after the network's stability) you are repeating the mistake of which you are fighting against.
> 
> An interesting video to watch that relates to this and to Google: https://www.youtube.com/watch?v=d_zt3kGW1NM&feature=youtu.be

I don't think so. We calculated validators token allocation according to the high cost of maintenance. Problems can occur only in a case where all validators will just hodl for a long period of time and burn their offchain money reserves. Also, the same issue can be archived just by someone keep buying tokens from a market gaining a really huge stake and at some point launch a set of validators.

Btw, nice point about network security. As I see, each new chain introduces higher requirements for validators. The higher threshold of validator entry, the more power validators will have.  We, as a decentralized community, definitely should find a way to reduce the political power of validators and make them just do business.

**Comment by xhipster** [comment]
> Fund Request

It is more about things we really wish to use. As of Fund request they have not reach this yet

**Comment by xhipster** [comment]
> after time validators start to have a lions share of the network

Basically @hleb-albau answer the question. Just want to add, that validators must cover the cost of validation by selling tokens to users. As validating business expected to be highly competitive, we do not expect huge validators margins. Hence we expect the majority of tokens will end in user's hands.

**Comment by serejandmyself** [comment]
Thanks for the answers.

I am positive that you guys know what you are doing =)

I only like to point you out to those things =)

In any case, I still think that a high cost of a product, does not mean that the manufacturers need to owe more money than the car drivers ;-) And it definitely doesn't mean that the car producers need to call out shots. They obviously need to cover their costs in order to produce cars, but in a synergic environment, the car production process and its revenue share would be as distributed as possible. I am not calling for socialism, but manufacturers should not be more important than the users. The car engineers - maybe at some point (otherwise there will be nothing to produce or drive) =)

**Comment by serejandmyself** [comment]
In any case - you answered the question. 

"Majority of tokens will be in users hands"

I guess the diagram is a bit misleading then, as it lead me to thinking that it's not that way.

**Comment by xhipster** [comment]
The diagram show cohorts if capital not channging hands. The type of diagram btw.. I got it from Vitalik projection during Ethereum luanch. It is impossible to predict how much miners will sell.
