### ISSUE TITLE
@asadovka proposal for entering cyber.Congress

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#178]
Lots of talking and conversations on this topic were during almost a year. I think the time to bring this thing to life has come.

According to Congress' whitepaper, there are several key functions it runs. Some of them I actually support and try to develop:

- Community building: continuous development of community on Gitcoin
- Delivery pipelining: improving our development pipeline
- Roadmap evolution: keeping the roadmap up to date and rethink it every block
- Sprints run: planning of 2-week sprints on Mondays, closing sprints on Fridays
- Forecasting: happens at the end of every sprint
- Visual perfection: visual can be fun and sexy

I want to improve not only these points, but also try to make the best of the rest functions

Also currently I am the person, who is responsible for Cyb project - delivery of development and design.

@xhipster @litvintech @hleb-albau, need your thoughts, review of my work, and actions on it.

**Comment by litvintech** [comment]
@asadovka I'm soon will be ready for discussing this with @xhipster @hleb-albau , need to prepare major points about proposal. As soon as we finish winter funding
Anyway, I think here should be more powerfull description of your proposal. @asadovka

**Comment by asadovka** [comment]
@litvintech you're right. I think we should communicate live first, and than make points of what I can propose. Currently, this issue is more like a reminder.

**Comment by xhipster** [comment]
General feedback: I will return to this decision after several things happen:
1. Browser vision will become sustainable
2. I will finish mentorship on resource management
3. We will have one more proposal for Congress member

**Comment by xhipster** [comment]
Not relevant anymore
