### ISSUE TITLE
Process payments for sprints 26-27

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#181]

**Comment by litvintech** [comment]
payments proccessed

**Comment by asadovka** [comment]
@litvintech @xhipster @hleb-albau please, process tx for @dimakorzhovnik

**Comment by litvintech** [comment]
@asadovka done

**Comment by asadovka** [comment]
@hleb-albau @xhipster waiting for your confirmation

**Comment by hleb-albau** [comment]
@asadovka right now done!
