### ISSUE TITLE
Setup IPFS cluster powered by congress

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#182]
- [ ] Update IPFS on Earth. Provide config for others. @hleb-albau 
- [ ] Install IPFS on Mars/Moon. @litvintech 
- [ ] Install IPFS-cluster on Earth/Mars/Moon @litvintech

**Comment by serejandmyself** [comment]
@mrlp4 this has been done, right?

**Comment by mrlp4** [comment]
Yep, done could be closed
