### ISSUE TITLE
Introduction to related communities

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#195]
- Ipfs
- Ethresearch
- Web3
- Cosmos

What else?

**Comment by serejandmyself** [comment]
- Urbit
- Ethermint (I would imagine that those communities are not going to be == Cosmos)
- IOTA (in terms of IoT and a global search machine - I imagine its a match made in heaven)
- MaidSafe (is there a community?)
- FOAM
- Melon (I think that for a fund its vital to be able to understand what all chains have to offer)

**Comment by serejandmyself** [comment]
@xhipster #219

**Comment by serejandmyself** [comment]
I will add this here, as this is most appropriate place, without doubling issues:

- Reddit:
		google, Futurology, artificial, cyber, hacking, Cyberpunk, technology, ipfs, 			CryptoCurrency, OpenBazaar, cosmosnetwork, FreeSpeech, MachineLearning, 		Libertarian, BlockChain
- bitcointalk
- twitter
- https://discuss.ipfs.io/
- own telegram group
- own website / blog
- github / gitcolony / gitcoin
- https://webchat.freenode.net/:
		 truth / ipfs / bitcoin 
- Some crypto media
- Conferences? / Hakatons
- Atom community:
		telegram, real-life, 
- ae, gri, cortex
- nvidia forums
- miners 
- urbit, foam, everpedia, decentraland
- steem, golos, CW
- galt


- https://riot.im/app/#/room/#cosmos_validators:matrix.org
- https://forum.cosmos.network/c/validating

- https://github.com/interchainio/funding

**Comment by serejandmyself** [comment]
One more very important community. I am not sure as of today how to approach them, but I am adding this as it is a must IMO:
Cryptography digest newsletter (the original mail based newsletter where the Bitcoin paper was send, still going)

**Comment by serejandmyself** [comment]
https://news.ycombinator.com/

**Comment by serejandmyself** [comment]
Ledger community

**Comment by serejandmyself** [comment]
Closed in favour of #289
