### ISSUE TITLE
Create awesome web3

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/congress#198]
Basic idea is to start a reputation formation @litvintech talked about on last Congress meeting from the curated awesome list.

I suppose @SaveTheAles can lead this effort as ~20% of his time.

I can curate and support initial publishing as well as reviewing pull requests.

Also, it will help @asadovka and browser team to form better expertise in the field.

**Comment by serejandmyself** [comment]
Looks like this has been somewhat done by others and by the web3 journal. Seems absolutely irrelevant @xhipster

**Comment by mastercyb** [comment]
Not relevant
