### ISSUE TITLE
Lets make demos in English

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#200]
We should share our plans and demos for community as fast as it possible
Here is the best way to make it with YouTube streams like [ipfs do](https://www.youtube.com/watch?v=hGkVST8H-Q8)

I believe we can start with cyberd team just to show how it goes. In demos, they can explain fixed bugs and new features, and answer to the questions from chat. Guys almost ready for that. What do you think? 

@xhipster @litvintech @hleb-albau

**Comment by serejandmyself** [comment]
@SaveTheAles wanna do this?

**Comment by serejandmyself** [comment]
@SaveTheAles ?

**Comment by SaveTheAles** [comment]
@serejandmyself I believe we're doing it already in our weekly dev meetings

**Comment by serejandmyself** [comment]
Ok, I guess I was referring to what you wrote about youtube. Let me know if I can help

**Comment by SaveTheAles** [comment]
Actually, we can close this issue
It's not relevant in this condition

@xhipster ?
