### ISSUE TITLE
A bit more structure to congress repos

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#208]
The following quite simple fings must be done to bring more structure to congress repos:
1. Library/wiki must be moved under congress/wiki
2. Library/paper must be moved under congress/library. instead of pdf use ipfs links
3. Archive repos move to https://github.com/cybercongress/congress/blob/master/archive.md

Previously agreed with @SaveTheAles

**Comment by SaveTheAles** [comment]
I've made it
https://github.com/cybercongress/congress/tree/master/library

@xhipster
