### ISSUE TITLE
New structured cyber•Congress site init

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#209]
At the moment we have useless site https://cybercongress.ai/ as a face of our team. I and @xhipster are in agreement to merge wiki.cybercongress.ai and cybercongress.ai . 

My proposal is to build upon an ipfs.io site as good template. Also, use their ipfs deploy mechanism as https://github.com/ipfs-shipyard/ipfs-dns-deploy

Site must contain main page with message, about, Implementations, team and footer sections. Also, at header the site should have links to blog as blog.cybercongress.ai, docs as wiki.cybercongress.ai and forum as discuss.cybercongress.ai. Blog should support rss. All sites should place in one directory ***congress***. 

Style of site should be same as https://cybercongress.github.io/gravity/?path=/story/examples-cyber--index

In addition, we must save very useful feature as filling site (docs, blog, etc.) with .md files for quick, automatic and easy editing.

**Comment by xhipster** [comment]
As a result of discussion with @SaveTheAles:
There must be on CMS to rule them all. Basically, we need one simple, fast and permanent tool for 3 basic tasks: blog, docs, and landing pages. We don't need subdomains for different tasks as it dilutes relevance in existing search engines. Also, we found that rss functionality is critical. Also, ipfs publishing from the box is also cool. Hence we decide to abandon mkdocs in favor of existing ipfs blog. We will add some markup for wiki pages manually, and may the force be with you...

![yoda-may-the-force-be-with-you-michael-greenaway](https://user-images.githubusercontent.com/410789/58262892-60344b00-7d7b-11e9-9b69-9b9a88a19feb.jpg)

**Comment by SaveTheAles** [comment]
@xhipster I believe that we can close this issue with our new site

**Comment by xhipster** [comment]
Yep! I think now the site is (almost) amazing :-)
