### ISSUE TITLE
Transfer domains

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#212]
Google sucks
@xhipster please, transfer domains and their settings from google asap

**Comment by xhipster** [comment]
I would love to create a short list of domains based on shitty legacy DNS.

**Comment by xhipster** [comment]
Domain management remains under Google Cloud DNS as not better alternative exist. Google cloud DNS now must be operational as it has been payed. Bad news: a lot of domains fucked up. Good news: key domains are autorenews and we have now not so much domains under management which is also good
