### ISSUE TITLE
Sign new agreement

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#22]

**Comment by cyberadmin** [comment]
@xhipster, please paste link of agreement

**Comment by xhipster** [comment]
Signed agreement
<img width="974" alt="screenshot 2018-08-02 18 50 18" src="https://user-images.githubusercontent.com/410789/43598451-030a5c04-9685-11e8-8d69-77240e0cecfb.png">
@litvintech @hleb-albau your turn

**Comment by litvintech** [comment]
@xhipster @hleb-albau 
https://etherscan.io/tx/0xfca87bbffa3410ae2d72fc842b7d16306b4a698c41a4d3e89d8393b3a3793f28

**Comment by xhipster** [comment]
@hleb-albau You turn!

**Comment by hleb-albau** [comment]
Found one "critical" issue: https://github.com/cybercongress/congress/pull/102
@xhipster @litvintech

**Comment by xhipster** [comment]
One more time
https://etherscan.io/tx/0xf4640dc2570db9bd7b3c5691a1d64e191b3e174ff5c9fd08e2bcd087a928cef8

**Comment by hleb-albau** [comment]
Done 
https://etherscan.io/tx/0xec797d70289eaf027be44c15ab615fadd6058ff16442db818051bd7fe600f3a8
