### ISSUE TITLE
Takeoff proposal

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#220]
[Details](https://github.com/cybercongress/congress/blob/master/friends/prepare-for-takeoff.md)

**Comment by xhipster** [comment]
Its kinda the most important task for us right now
- Release 0.1.1
- Deploy cyber•Foundation GOL to mainnet
- Reach as much as possible validators

**Comment by serejandmyself** [comment]
@xhipster I would add #307 to the list

**Comment by xhipster** [comment]
Bump

**Comment by xhipster** [comment]
Bump

**Comment by xhipster** [comment]
Bump

**Comment by xhipster** [comment]
Bump

**Comment by xhipster** [comment]
Today the scope and timeline for the proposal has been defined

**Comment by serejandmyself** [comment]
https://cyber.page/governance/2
