### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#246]
Counter before launch (18.00 GMT friday)
Button in the center: cyber.page

Footer:
1. cyber.page
2. cyberd.ai
3. cyb.ai
4. [aragon](https://mainnet.aragon.org/#/cybercongress/0x4feb2bcc5907e7779130c093eef8fb44502c1330)
5. github
6. forum
7. rss
8. twitter
9. telegram

**Comment by serejandmyself** [comment]
This has been done, no?

**Comment by dimakorzhovnik** [comment]
@serejandmyself, done
