### ISSUE TITLE
Infrastructure setup for take-off 

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/congress#248]
- Nodes allocation and setup 
  - [x] Cyberd sentry / search  nodes
  - [x] Seed nodes 
  - [x]  Validators 

- Security setup 
  - [x] Improvement of sign-in security + guide 
  - [x]  Firewall + guide 
  - [x] Backups and mirroring

- Monitoring setup 
  - [x] Setup Grafana monitor node + create all in one dashboard +guide 
  - [x] Setup prometheus above all nodes + connect to grafana 
  - [x] Alerting setup to email + Telegram Bot 

- Side services for launch 
  - [x] Eth nodes + backup
  - [x] Eth wss endpoints
  - [x] Cosmos nodes + backup
  - [x] Cosmos mongo with transactions
  - [x] IPFS cluster 
  - [x] IPFS gateway

**Comment by xhipster** [comment]
Please enrich the list with endpoint and urls which are necessary

**Comment by mrlp4** [comment]
Created IPFS cluster/gateway
https://gist.github.com/mrlp4/ec4a19aa701b52365f5ed6cd8f6d046d

**Comment by mrlp4** [comment]
Closed as far as completed.  Some new tasks moved to [repo](https://github.com/mrlp4/infra_congress).
