### ISSUE TITLE
Cyber app for Ledger 

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/congress#249]
On base of cosmos app design cyber app to use with cyberd chain as hardware wallet.

### Why Is this Needed?
Currently it is possible to use Cosmos app for signing transactions at cyberd chain, but necessary to have own.
*Summary*:

### Definition of Done
Fork cosmos app, adopt all necessary as headers, logo's, etc. Contact with Ledger to publish it to Ledger Live store.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by xhipster** [comment]
It seems that Ledger Cosmos app works for cyberd

**Comment by serejandmyself** [comment]
This is done, isnt it?

**Comment by serejandmyself** [comment]
I have been in contact with Ledger to publish us on the assets page (euler5 tokens and then mainnet). But to my sadness they are very slow at handling cases

**Comment by xhipster** [comment]
I am not sure that we actually need this. What extra benefits we got except extra work for maintaining this app? I have better idea: I am going to distribute cyb to Ledger. So this will be the app that allow for multi-network signing in Ledger including cyber network.
