### ISSUE TITLE
Write proposal for urbit drop

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#253]
Drop out of main distribution: Urbit - up to 1%, divided into 3 bags (planets: 40%, stars: 30%, galaxies: 30%)

UPD: 
~~Potential proposals after governance module is in place: foam, everpedia (to discuss)~~
(transfer to /ecosystem/backlog)

**Comment by xhipster** [comment]
- update Gift section of whitepaper
- describe distribution methodology
- scripts for calculation
- blog post with stats and idea

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/blob/master/ecosystem/communities/urbit/urbit.md

**Comment by serejandmyself** [comment]
Initial work is done. Now its about ongoing work to find a developer and moving the issue to the correct repo I believe (please re-open if not)

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/issues/261
