### ISSUE TITLE
Add Urbit ID for team members

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#256]

**Comment by xhipster** [comment]
<img width="487" alt="Screenshot 2019-10-29 at 14 44 18" src="https://user-images.githubusercontent.com/410789/67768181-a6908300-fa5a-11e9-9673-df4b62489705.png">

**Comment by serejandmyself** [comment]
How do you see this as being added? For the time being I just added mine to the team page.

**Comment by mastercyb** [comment]
Not actual for now
