### ISSUE TITLE
Cyber app for Urbit

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#261]
Following this demo https://github.com/yosoyubik/urbitcoin
I think it will be awesome to introduce Cyber to Urbit community with cyber-app

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/issues/195

**Comment by serejandmyself** [comment]
Needs a review: @litvintech @xhipster 

https://github.com/cybercongress/congress/blob/master/ecosystem/communities/urbit/urbit.md

**Comment by xhipster** [comment]
I think that proposal is nice

**Comment by mastercyb** [comment]
Not actual
