### ISSUE TITLE
Introduce Congress and Cyber Foundation to Aragon community

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#262]

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/issues/195

**Comment by serejandmyself** [comment]
@litvintech Have you had any particular ideas in mind?

**Comment by xhipster** [comment]
According to their [recent report](https://blog.aragon.org/aragon-by-the-numbers-after-one-year-on-mainnet/) the biggest org holds not more than $0.5M. I suppose cyber•Foundation could surpass it. Hence value proposition is the bigger biggest org which has not been formed yet truly. I doubt they will mention us somewhere unless that will become true :-(

**Comment by serejandmyself** [comment]
Initial work is done:
https://wiki.aragon.org/about/projects/

Continuous work moved to #195
