### ISSUE TITLE
cyber~Ecosystem development paper

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#263]
Discussion and help wanted:

https://github.com/cybercongress/congress/blob/master/ecosystem/cyber~Ecosystem%20development%20paper.md

**Comment by xhipster** [comment]
Document become more and more interesting. I would restructure the document a bit in accordance with goal/audience/metric logic so it would be clear which effort are connected with what goal. I would join to this work, but I need to finish wp and gol provision first. 

Also, one point is absent. I would mention cyberCon as we discussed and principles behind it.

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/blob/master/ecosystem/cyber~Ecosystem%20development%20paper.md
