### ISSUE TITLE
Add info to the main page of https://cybercongress.ai/

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#270]
https://cybercongress.ai/ needs more info on what it is. It could be a FAQ link or a link to a post. Possibly a third button (next to `validator` and `whitepaper`)

**Comment by serejandmyself** [comment]
I think we can add this (it might not have the most info, but it certainly is MORE than what we have now):

https://github.com/cybercongress/congress/blob/master/ecosystem/ELI-5%20FAQ.md

**Comment by serejandmyself** [comment]
@xhipster

**Comment by serejandmyself** [comment]
IMHO, it can look like this:

         Cyber: like google but cyber
    Testnet euler-dev at block 283 386
`Become a validator` `Whitepaper` `FAQ`

**Comment by xhipster** [comment]
`FAQ` `App` `Whitepaper`

**Comment by xhipster** [comment]
IMHO we need to rout main funnel to app, and use FAQ in different contexts

**Comment by serejandmyself** [comment]
My main concern now is the offline tests that I run on a about a dozen of people. The feedback is unified (and I agree): for someone who opens the front page now, is impossible to understand whats going on, without really diving deep. 

As you probably analyzed more projects than myself, you know how annoying it is to open a projects website and be left without an understanding whats going on =)

It doesnt have to be the FAQ at all =)

Im just concerned that people really arent getting what the project is about from looking at the website and the rabbit hole has a very high entrance rate

**Comment by xhipster** [comment]
Cybercongress is a site of an organisation and was not intended as front app, though https://cyber.page is

**Comment by xhipster** [comment]
Maybe we will add FAQ in the top menu?

**Comment by serejandmyself** [comment]
I think it might be a good idea )

**Comment by serejandmyself** [comment]
I think its irrelevant for now. The congress webiste shouldn't have the FAQ. Possibly, in the future it will have links to own staking provider / great web journal
