### ISSUE TITLE
Publish videos from Game of Links launch

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#283]

**Comment by serejandmyself** [comment]
This is [done](https://www.youtube.com/channel/UCUfxwbONrtEFeCHOA3gHT-g/videos)

**Comment by xhipster** [comment]
I think it would be nice to cyberlink sources of videos

**Comment by serejandmyself** [comment]
> I think it would be nice to cyberlink sources of videos and pin them to our cluster

Sure. Changed the title and the type of the issue

**Comment by xhipster** [comment]
I've expanded the name, because the task currently is partially done
