### ISSUE TITLE
Reach sustainable income flow for cyber~Congress

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#302]
After studying the current situation I have come to the following conclusions:

1) Jumping ahead, to after donations: the congress DAO will have one cemented source of income, the staked ATOM. This isn't good, hence it needs diversification.

PS. We can also add to this, the staking of CYB tokens

2) The other sources of income for the congress DAO, are what I call `supporting income`, meaning that they are unstable, not frequent or not guaranteed. 

To divide them further into 3 categories (by time frame and sureness of income):
- Quite positive: governance proposals 
- Quite positive 2: Chaingear 
- Strongly fluctuated: Investments into decentralized beasts 
- Very distant: Future income of cyber~FundClassic

3) A solution to this, which kills several rabbits, is:
To start-up a validators business after the donations round. This will allow cyber to:
- Take part in validating strong and powerful chains under the name #fuckgoogle, meaning that if fuckgoogle makes a stance in each of those and takes an active governance position, cyber, in return, may get new users, partnerships, devs
- Diversify a strong and cemented source of income for the congress DAO, even if it's not large, it can be developed and grow over time

**Comment by xhipster** [comment]
Validation is the business requiring hard assets, hense it's impossible to decentralize it in some sense, hense makes cyberCongress weak. I would tend to develop completely virtual revenue in order to make us non vulnerable to majority of potential attacks. 
You also forget that cyberCongress already have revenue stream from Chaingear using which we live at least last 3 months. I expect it's possible to expand it. We just have not done any efforts though. 
We talk about validation with @litvintech before and the only way we can develop this business congress wide is to handle kinda 2of3 validators with PERSONAL responsibility for hradware

**Comment by serejandmyself** [comment]
2/3 is a one solution. Hence i think it should only be discussed after the donations. However I strongly believe this can make a huge input in terms of guerilla PR.

PS. Added chanigear to `supporting`,positive income source

**Comment by xhipster** [comment]
I would love to invest into tooling for kinda multisig validation, but a bit later with more resources.

**Comment by serejandmyself** [comment]
I agree. My main concern is not to repeat past mistakes and reach sustainability and diversification, whilst keeping true to our cause

**Comment by serejandmyself** [comment]
Possible validator list:

- [ ] [Cosmos](https://cosmos.bigdipper.live/validator/cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u)
- [ ] Cyber
- [ ] Kusama
- [ ] Polkadot
- [ ] Nucypher
- [ ] Desmos
- [ ] Solana
- [ ] Cardano
- [ ] FOAM
- [ ] Livepeer
- [ ] ETH 2.0
- [ ] Rchain

**Comment by serejandmyself** [comment]
Im curious to whether gitcolony can act as some kind of a multisig operator space for validator business

**Comment by xhipster** [comment]
@serejandmyself I created standalone discussion for fuckgoogle provider

**Comment by xhipster** [comment]
It could happens that [successful Takeoff](https://github.com/cybercongress/congress/issues/220) could be enough for sustainability

**Comment by mastercyb** [comment]
After recent fundings, it seems we have a kind reserve for fulfilling this goal. Accompanied with ethereum staking the target could be done

**Comment by mastercyb** [comment]
Done. Currently we have more than 500 ETH under management. Given our burn rate we could sustain our operations for years.
