### ISSUE TITLE
Videos from Euler-5 launch

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#303]
A reference to #283 

- [x] Cut all 6 videos
- Infrastructure
- Ecosystem
- GoL
- Cyb
- Cyber
- Launch video
- [x] Make time frames for videos
- [x] Make descriptions for videos
- [x] Create a playlist [here](https://www.youtube.com/channel/UCUfxwbONrtEFeCHOA3gHT-g/playlists)
- [x] Publish 5 videos in playlist
- Infrastructure
- Ecosystem
- GoL
- Cyb
- Cyber
- [x] cyberlink videos to IPFS cluster (@SaveTheAles)

**Comment by serejandmyself** [comment]
@SaveTheAles you can pin the videos now

**Comment by SaveTheAles** [comment]
@serejandmyself 
added
now videos available by following search phrases

```
ecosystem presentation - > QmWDYzTXarWYy9UKC7Ro4xMCdSVseQPbmdnmTYsJ9zGTpK

euler-5 launch -> QmVgxX3TVntSNRiQ1Kd8sE8zvEKkbEgb8PaMnA4N7w7pKS

cyb roadmap -> QmQWdLA8ppSCE1YALwRCwqRpvThLgpbD1acN7netCuTGZZ

cyber development roadmap- > QmSRVe5PFZAaHJgwThL1zLa3qkUs9111WDdo4VPvmvMDtc

cyber node and infrastructure set up -> QmdZPgzkhNfaC7cgnW8TrztSr7jwHVhp84zqajN14ydUEH

game of links workshop -> QmYxLd6QhrCZx4weuT4W4B8pZ365xF6Ywt1itqBBcXmYjE
```

You can also make cyberlink with key phrases you would love
this is the Great Web. nobody cares
