### ISSUE TITLE
Cosmostation campaign

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#304]
Include:
- [x] development of the campaign text/landing
- [x] payment coordination
- [x] control of execution
- [x] tracking results

**Comment by serejandmyself** [comment]
- Web wallet (logo and text. 60 characters)

- Explorer main screen (logo and text. 60 characters)

- Explorer tx detail (*Standard image size : 500px * 80px (Mobile) / 850px * 90px (Tablet) / 1200px * 90px (PC)

**Comment by serejandmyself** [comment]
**Web wallet (internal page):**
- No gift, no hunny! Claim your free bootstrap fuel!
- Logo of cyber (purple pic) included
- Banner should be targeted at a specific wallet and leads to cyber.page and the corresponding wallet. [Example](https://cyber.page/#/search/0xdc76cd25977e0a5ae17155770273ad58648900d3)
- Issues: currently no call to action button or explanation link on how to claim. IMO, a simple `Bootstrap here` button is needed under the gift
- Second Issue - there should be a button here that leads to GoL `Save the galaxy` | `Start linking`

**Main page of the explorer:**
- Cosmonauts! Join Game of Links - the intergalactic contest!
- Logo of cyber (purple pic) included
- Static banner with link to [GoL rules](https://cybercongress.ai/game-of-links/)
- Issue: no call to action in the rules either... IMHO, could be a button right at the top of the rules `Save the galaxy` | `Start linking`, which lead to.... 

**Explorer tx detail:**
- Text over a black background with 
- CYBER: Bootstrap free fuel and join the intergalactic tournament - just link it!
- Possible explanation underneath the above text: cyber - a decentralized google for provable and relevant answers
- Logo to the right of the text (same purple logo)
- Image is clickable and targeted. Leads to [gift page](https://cyber.page/#/search/0xdc76cd25977e0a5ae17155770273ad58648900d3) of the corresponding address that made the tx in question

**Comment by serejandmyself** [comment]
[Payment proof](https://etherscan.io/tx/0x28c1bc3f4de2d1f6862645074ba8a5e5d0bb156ae85b2bcb6979e0589477186e) for 01/03/2020  - 01/04/2010

**Comment by serejandmyself** [comment]
Need help with image for Explorer account and tx detail banner

- Size : 500px * 80px (Mobile) / 850px * 90px (Tablet) / 1200px * 90px (PC)
- Design: purple cyber logo, text, button
- Design detail: black background, purple logo, white letters ?
- Text: 
Bootstrap free fuel and join Game of Links - the intergalactic tournament!
cyber: a decentralized google for provable and relevant answers
- Button: Claim gift

@xhipster

**Comment by xhipster** [comment]
I forgot, today I promise, will be ready

**Comment by xhipster** [comment]
@xhipster @litvintech 

- Address to transfer to:
0xD6E705C0BB892A0D59Bf0F04B76e95588b3AD417
- sum:
5.02 eth 
- reason:
Stakingrewards listing
- timeframe:
ASAP

**Comment by serejandmyself** [comment]
> @xhipster @litvintech
> 
> * Address to transfer to: 0xD6E705C0BB892A0D59Bf0F04B76e95588b3AD417
> * sum: 5.02 ETH
> * reason: Stakingrewards listing
> * timeframe: ASAP

Thats should be in #319 (the address is already there =)

**Comment by xhipster** [comment]
Yep, Thks

**Comment by xhipster** [comment]
![mobile](https://user-images.githubusercontent.com/410789/75032429-e1ef0b80-54a8-11ea-8d99-2e6693f41817.png)

Need @serejandmyself feedback, if ok - will do 2 others

**Comment by serejandmyself** [comment]
I like it

**Comment by xhipster** [comment]
![mobile](https://user-images.githubusercontent.com/410789/75032776-ad2f8400-54a9-11ea-81c7-15465e8c771a.png)

I tested it in real mobile and it looks also tiny. The new version

**Comment by serejandmyself** [comment]
I like less but I like it too =)

**Comment by serejandmyself** [comment]
Only one comment

**Comment by serejandmyself** [comment]
Right now, from reading the second banner, I get the impression that I have to pay for something

**Comment by xhipster** [comment]
![desktop](https://user-images.githubusercontent.com/410789/75033258-ce44a480-54aa-11ea-91ad-455f15fe121a.png)
![mobile](https://user-images.githubusercontent.com/410789/75033266-d13f9500-54aa-11ea-80e0-ac352851b626.png)
![tablet](https://user-images.githubusercontent.com/410789/75033271-d270c200-54aa-11ea-90e0-66375fb35400.png)

**Comment by serejandmyself** [comment]
Isn't it obvious that the person has ATOM though? He is already on the explorer )

**Comment by xhipster** [comment]
1. I am talking also about ETH
2. Trust me - It is not.
3. Feeling of exclusivity rise the conversion

**Comment by serejandmyself** [comment]
I am only giving my personal feedback. I feel like im being asked for something )

**Comment by serejandmyself** [comment]
But if you feel like it isnt, then Id say number 3 is the best

**Comment by xhipster** [comment]
Надеюсь с вашей конторой я в расчете :-)

**Comment by serejandmyself** [comment]
https://www.mintscan.io/

Other examples require a wallet. But its alive and working
