### ISSUE TITLE
Distributed web3 validator and provider

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/congress#305]
### Rationale
First, we want to [find sustainable model](https://github.com/cybercongress/congress/issues/302#issuecomment-583731419) for the organisation. Second, we want to have a good case of infrastructure provider for dapps we build. Third, it looks like it is necessary for moving the industry further. And the most important approaching this goal we must not loose ability to remain invulnerable and resilient to different attack surfaces.

### Solution
Find a universal way to validate networks using MofN signature approach in a setting where every signatory is independent hardware provider. On top that we can implement very cool economics.

## Implementation
Unknown

## Possible validator list:

_Originally posted by @serejandmyself in https://github.com/cybercongress/congress/issues/302#issuecomment-583731419_

- [x] Cosmos
- [ ] Cyber
- [ ] Kusama
- [ ] Eth2
- [ ] Polkadot
- [ ] Nucypher
- [ ] Desmos
- [ ] Solana
- [ ] Cardano
- [ ] Foam
- [ ] Livepeer
- [ ] Rchain

**Comment by litvintech** [comment]
It's only possible if chain support Sr25519, as I know now Polkadot support this and planned in Tendermint

**Comment by mastercyb** [comment]
Bad idea. We would have our own infrastructure for research purposes, but not for having operational overhead
