### ISSUE TITLE
Archive brain project

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#306]
## Rationale
Now we have a [brain](https://github.com/cybercongress/brain) project which is served through https://cyberd.ai. First, we now have a cyberindex - amazing working alternative. Second - support of current explorer is awful and a lot of features which must work are not working (e.g. list of cyberlinks for account). Third - cyber.page is tend to reach feature parity with current explorer at [0.1.2 version](https://github.com/cybercongress/dot-cyber/projects/5).

## Solution
Remove explorer from https://cyberd.ai after 0.1.2. release of cyber.page and create on this domain good source of knowledge on [cyberd](https://github.com/cybercongress/cyberd) implementation and tooling around it for developers (specs, docs, roadmap, cyberindex, wrappers, simulations, benchmarking). Hence cyber.page will generate traffic for average joe and cyberd will be dedicated for developers. The current brain project will be archived

**Comment by serejandmyself** [comment]
Archived
