### ISSUE TITLE
Upgrade to euler-6

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#309]
### Rationale
Currently we have at least one blocking error for continue Game of Links on top of euler-5: a bandwidth limiting bug which remove ability to correctly load the network. In addition there are some more errors with sync. According to launch protocol we have to act and relaunch the network. 

### Workflow
- Define allocation of euler-5 participants based on lifetime (other disciplines in fact were not activated): @Aha203 proposal to governance
- Export cyberlinks @SaveTheAles 
- Add ability to import cyberlinks in https://cyber.page @xhipster @dimakorzhovnik 
- Roll out 0.38.1 cosmos-sdk in order to mitigate risks of relaunch due to errors @litvintech 
- Fix bugs @litvintech 
- Prepare genesis of euler-6 @SaveTheAles 
- Coordination of launch euler-6: @Aha203 
- Infrastructure upgrade to euler-6 @mrlp4 
- https://cyber.page upgrade to euler-6 @dimakorzhovnik

**Comment by Aha203** [comment]
https://github.com/cybercongress/cyberd/projects/6 - the main project for upgrade

**Comment by SaveTheAles** [comment]
@serejandmyself 
Here is a workflow for soft e-5 -> e-6 relaunch with state saving

https://github.com/cybercongress/launch-kit/blob/0.1.0/migrations/e-6%20migration_proposal.md

**Comment by serejandmyself** [comment]
We've upgraded
