### ISSUE TITLE
Knowledge sharing for airdrop

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#31]
1. lecture to describe what airdrop is.
2. how will be airdrop implemented in congress token distribution.

**Comment by 21xhipster** [comment]
Let us starting from [this](https://docs.google.com/spreadsheets/d/14QX9oHt3a9zmOuMbrCaUMjP0AUibqUCu2wLyjjnC00c/edit#gid=430581565)

**Comment by xhipster** [comment]
Dublicate of https://github.com/cybercongress/cyberd/issues/5
