### ISSUE TITLE
The Great Web Journal 

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#311]
What:
Create a monthly journal about the state of the blockchain ecosystem

Name:
The Great Web (same as podcasts)

Style:
Monthly overview of important shit. 
Subheading / text / link
[Example of style](https://golos.io/@itsynergis/daidzhest-web-3-0-3-2020-1581403129083)

How to:
RSS / IPFS / .eth ? / whatever else

**Comment by xhipster** [comment]
Ive submitted the concept in a [new repo](https://github.com/cybercongress/great-web). IMHO the concept is fine. Lets track particular issues in standalone repo
