### ISSUE TITLE
Create a visualization of the metagalaxy for homestead doc

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#315]
Based on the listed [componentes](https://github.com/cybercongress/congress/blob/master/ecosystem/Cyber%20Homestead%20doc.md#cybermetagalaxy)

**Comment by serejandmyself** [comment]
#206

**Comment by mastercyb** [comment]
![IMAGE 2021-07-19 10:56:34](https://user-images.githubusercontent.com/410789/126123743-e6f632ec-0702-471a-9a6f-847ac51415ce.jpg)

Seems the task is solved
