### ISSUE TITLE
Take GA down from cybercongress.ai

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#318]
**TL;DR:**
Upon discussion on [this issue](https://github.com/privacytoolsIO/privacytools.io/issues/1646), a GA script on the [DAO website](http://cybercongress.ai/) was pointed out. After consideration with @xhipster it was decided to be taken down

**Call to action:** 
Take down GA from cybercongress.ai

**Comment by mastercyb** [comment]
Done
