### ISSUE TITLE
Get listing on stakingrewards.com

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/congress#319]
As previously discussed, list cyber as a network and cyber~Congress as a provider on [stakingrewards](https://www.stakingrewards.com/)

Cost: 1200 EUR for life

What is needed: A decision from the team to move forward

**Comment by xhipster** [comment]
Go on

**Comment by serejandmyself** [comment]
0xD6E705C0BB892A0D59Bf0F04B76e95588b3AD417

FYI. Will make an additional request for payment

**Comment by serejandmyself** [comment]
TO DO:

- [ ] Provide payment detail to team
- [ ] Oversee payment
- [ ] Get listing info from Mirko
- [ ] Provide info to Mirko
- [ ] Check listing

**Comment by xhipster** [comment]
@xhipster @litvintech 

- Address to transfer to: 0xD6E705C0BB892A0D59Bf0F04B76e95588b3AD417
- sum: 5.02 ETH
- reason: Stakingrewards listing
- timeframe: ASAP

**Comment by xhipster** [comment]
@litvintech The [proposal](https://mainnet.aragon.org/#/cybercongress/0x4feb2bcc5907e7779130c093eef8fb44502c1330/vote/37/) is ready to sign

**Comment by serejandmyself** [comment]
https://www.stakingrewards.com/asset/cyber
