### ISSUE TITLE
Design cyber•Style

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#32]
We need logos of all our projects and congress itself

**Comment by cyberadmin** [comment]
@xhipster - create tasks

**Comment by xhipster** [comment]
@asadovka @Olga584 Please, check

**Comment by xhipster** [comment]
It seems that we now have clear, sound and very diversified style across projects we do. Thanks @Olga584.

It take a lot of time to extend this foundation, but for now I think this epic is done
