### ISSUE TITLE
Communicate congress ideas

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#35]
Good example is [Gitcoin](https://gitcoin.co/mission)
Collect ideas and principals from all projects and put it in 1 doc. Compare with Goals, Value and Stack in @21xhipster [contract](https://github.com/cybercongress/congress/blob/21-agreement-proposal/contract.md). 

Generated congress ideas as result.

**Comment by SaveTheAles** [comment]
Add [doc](https://github.com/cybercongress/congress/blob/master/Organization/projects_values.md). Fill it please according to your projects.
