### ISSUE TITLE
Landing pages for key projects

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#36]
We need landing pages for cybercongress, cyberd, chaingear and cyb. Also we need to have nice presence across communication channels

**Comment by cyberadmin** [comment]
@Olga584 Please, start from merging @litvintech  presentation

**Comment by xhipster** [comment]
https://cyberd.ai/

**Comment by asadovka** [comment]
@xhipster @litvintech @hleb-albau do we need something more? which status does this epic have?
