### ISSUE TITLE
Markdown table is not rendered

### ISSUE THREAD

**Issue by sxiii** [cybercongress/congress#397]
### Current Behavior
Open https://cybercongress.ai/docs/cyberd/supported_gpu_list/
See, that markdown tables aren't rendered at all.

### Log
![image](https://user-images.githubusercontent.com/575925/82553981-5d725e80-9b65-11ea-9e40-23f97468c0a3.png)

### Expected Behavior
Markdown should render tables as tables, not as text.

### Reproduction
Open https://cybercongress.ai/docs/cyberd/supported_gpu_list/
See, that markdown tables aren't rendered at all.

### Solution
Fix markdown rendering issues

### Definition of Done
Tables correctly show up in top-10 browsers

**Comment by mrlp4** [comment]
Fixed in [#526](https://github.com/cybercongress/go-cyber/pull/526)
and #399 
Thanks @sxiii
