### ISSUE TITLE
Port forwarding links to add into the manual

### ISSUE THREAD

**Issue by sxiii** [cybercongress/congress#398]
### Rationale
https://cybercongress.ai/docs/cyberd/port_forwarding_guide/#port-forwarding

You're saying you can help people to configure the port routing in devChat while there are dozens of websites that have huge guides and catalogs that allow users to type-in router model and see the screenshots for port forwarding setup.

### Solution
Add websites such as:
* https://portforward.com/router.htm
* https://setuprouter.com

Instead of asking for help in devChat, users could easily help themselves. And no need to forward them into these websites manually.

Additionally, I want to note that the article has grammatical errors:
https://cybercongress.ai/docs/cyberd/port_forwarding_guide/#port-forwarding
For example, here: ```and much more we’ll has in the future```.

### Implementation
Add the important links & fix the article grammatics & syntax. Spellcheckers!

**Comment by mrlp4** [comment]
Thanks for contribution @sxiii 
All your's proposals was applied [here](https://github.com/cybercongress/go-cyber/pull/526)
Pull is to the different repo - cause we handle all docs there.
