### ISSUE TITLE
Restructure documentation according to projects

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#40]

**Comment by SaveTheAles** [comment]
@xhipster @litvintech @hleb-albau 
for now i see all documentation as big interactive presentation like Prezi
[Here](https://prezi.com/view/sQIo1yAFsbHMKNZFMeJr) you can see how I structure cyber-search and chaingear

**Comment by xhipster** [comment]
@SaveTheAles Please avoid using additional proprietary services without access to source

**Comment by SaveTheAles** [comment]
Available at https://cybersearch.io/
