### ISSUE TITLE
Economics design competetion

### ISSUE THREAD

**Issue by Vgk88** [cybercongress/congress#415]
ENIP: 1
Title: Economical improvement compettion and incentivized distribution for the Euler network
Authors (alias): cyberG
Status: Draft
Type: ENIP
 
Abstract:
The main idea of this proposal is that the reward pool outlined in [proposal #7 of Euler network](https://cyber.page/governance/7) (equals to roughly 4.6 TEULs) can be increased via delegations to existing and future validators. This will help to onboard and support validators and motivate existing validators. It will also help to distribute more tokens in the future. The secondary idea is to help reward the community for testing and using new features of the Euler network. .
 
Motivation:
After the lunch of Cyber's mainnet, the Euler network will need additional support for its growth. Using delegation will make it possible to increase the distribution reward pool. Using gamification will help to make the distribution process more interesting.
 
'2' 3-of-5 multisig accounts will allow the community to distribute rewards in a more secure way.Reward for the participants of the first distribution pool (MS1) is 0.3 TEUL (0.1 each). Reward to the participants of the second distribution pool (MS2) is 10% of the validation rewards. These numbers are, only, initially proposed and should be voted on by the community at each step of the voting. 
 
My motivation as the creator of this proposal is that I can choose in which distribution pool I want to participate (MS1 or MS2) and I will be able to choose into which MS reward pool the participants will go.
 
Stage 0 is the vote on this ENIP itself, if passes participants of the MS pools will be chosen and thereafter they will have to use on-chain governance at each stage of the implementation to make it easy and decentralized.
 
Reference implementation:
Stage 0: Defining the objectives of the distribution of these tokens
- long-term support of the Euler network
- stimulation of validators for stable operation
- reward developers and communities for creating tools for the Euler network
- rewarding users for testing applications on the Euler network
- growing the community
- rational use of funds
 
Stage 1: Chose the participants of the multisigs
- 2 multisig wallets
- 3 out of 5 (@serejandmyself + 2 members from the cyber~Congress team + 2 community participants)
- I can choose which multisig I will participate in and which members go to which MS
- Community members can submit their applications for participation
 
Stage 2: Distribution of funds to multisigs and chossign the distribution conditions
Multisig1 (MS1): 2.3 TEUL = 2 TEUL (distribution) + 0.3 TEUL for MS1 participants
 
Multisig2 (MS2): 2.3 TEUL = 2 TEUL (delegate 10 validators to the mainnet) + 0.3 (used to help new validators launch nodes before Cyber's mainnet)
 
MS2 participants receive 10% of the delegation reward. MS2 members cannot receive their reward until Cyber's mainnet. They should take the rewards at a constant (for easier calculations), where 10% goes to them and the other 90% of the reward will go to further causes (described below).
 
Multisig participants should use voting to implement the proposal stages and for any additional ideas.
 
Stage 3: Pre-mainnet distribution
MS1:
- airdop for testing cyber.page and other tools (1TEUL). Airdrop for 100 participants. Maximum reward 10 GEUL per participant
Examples of tasks:
- make a cyber tweet
- comment cyber tweet
- subscribe to the cyber page account on cyber Twitter
- subscribe to 3 accounts
- upload 10 cyberlinks
- load web page
- link web page
- load something via crawler
 
Examples of rewards outside of the airdrop:
- carry out the reward for creating tools for Euler
- tools for redelegation
- tool for monitoring validators
- creating tools for indexing
- linking tools
 
MS2
- Select 10 validators for delegation and delegate to them
- Multisig participants cannot be in the list of validators for delegation
- Distribute 0.3 TEUL (gradually) to new network validators.
 
If MS1 does not distribute the rewards before the mainnet, then these tokens should go to multisig 2
 
Stage 4: Post mainnet
- Claim the first awards by multisig 2 participants
- Redelegation if required
- Continue to reward tools by MS1
- Support for new validators by MS2
- Reward for testing new features in Euler

**Comment by serejandmyself** [comment]
This is the only ENIP submitted. Follow up publishing is a question of desire from the submitter
