### ISSUE TITLE
Add cyber-rs and cyber-wallet-generator

### ISSUE THREAD

**Issue by deadblackclover** [cybercongress/congress#416]
We have developed a library `cyber-rs` and wallet generator using the Rust language.

cyber-rs:
https://github.com/CipherDogs/cyber-rs
https://crates.io/crates/cyber
https://docs.rs/cyber/0.1.3

cyber-wallet-generator:
https://github.com/CipherDogs/cyber-wallet-generator
https://crates.io/crates/cyber-wallet-generator

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/blob/master/ecosystem/Cyber%20Homestead%20doc.md#community-maintained-profiles-and-tools
