### ISSUE TITLE
Outdated graph url

### ISSUE THREAD

**Issue by Fogapod** [cybercongress/congress#418]
Hello, I've been reading FAQ, looks like there is a broken link in https://github.com/cybercongress/congress/blob/master/ecosystem/ELI-5%20FAQ.md#what-is-a-cyberlink: [graph link](https://cyber.page/graph) says not found, not sure why. Did graph location change?

**Comment by serejandmyself** [comment]
@Fogapod Hey, no. The link isnt broken (well it is). The graph got too big to render on local machines by users and we decided to take it off until we think of a better solution to render it in a non centralized manner by each user separately. 

This is just a graphical representation of the graph, although a very cool one

**Comment by serejandmyself** [comment]
Closing this for now. Will let everyone know in public when there is a solution from the technical team

**Comment by Fogapod** [comment]
Could you maybe copy this text or link this issue on /graph instead of generic "not found" template? Since this endpoint is mentioned in multiple places other people may get confused as well.

**Comment by serejandmyself** [comment]
@Fogapod great idea. Will go trough the link in the docs now

**Comment by Fogapod** [comment]
https://github.com/cybercongress/congress/commit/c0b13c0686abb665f07476edadb2127d822e179f I didn't mean replacing all links in all documentation, I suggested putting a placeholder on /graph endpoint in on cyber.page itself until it's fixed.
There is at least 1 place on website that has link to /graph, so changing documentation isn't enough

**Comment by serejandmyself** [comment]
@Fogapod I get it. Its just not something I can do from my side =)

The answer I got form the team is that we are not far away from fixing it, so they would rather fix it then make a placeholder. Although I think placing placeholders is a good practice altogether and should be done constantly. I will try to persuade our fron end dev to do one until its fixed. Thanks
