### ISSUE TITLE
Script collecting docs from project /docs folder

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#42]
Write a script-collector to collect docs from project to '/docs' folder

**Comment by SaveTheAles** [comment]
@hleb-albau connect it to circleCI

**Comment by arturalbov** [comment]
For each repo:
To enable changelog autogeneration for repo next should be done:
- [ ] [Generate access token for cyberadmin](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
  
![imageedit_12_5457681186](https://user-images.githubusercontent.com/7107023/42378166-f712c5a0-812e-11e8-873f-639ccff4d7f8.png)

- [ ] Add generated token as env **DOCS_GITHUB_TOKEN** variable in Circle CI of your repo.
- [ ] [Add CircleCi job](https://github.com/cybercongress/cyber-search/pull/240/files#diff-1d37e48f9ceff6d8030570cd36286a61)  to your repo **.circleci/config.yml** file. Replace project name where it's needed
![imageedit_9_9098860524](https://user-images.githubusercontent.com/7107023/42378173-fc7f608e-812e-11e8-98df-af8f1e5c3020.png)
