### ISSUE TITLE
 link on main cybercongress.ai to cyberd.ai not working

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/congress#432]
cyberd.ai is no longer maintained. remove\update link to it  from cybercongress.ai

<img width="540" alt="Screen Shot 2021-02-03 at 7 35 29 PM" src="https://user-images.githubusercontent.com/38989909/106742145-969d2100-6657-11eb-929e-5683068e9a5a.png">

**Comment by mastercyb** [comment]
Not relevant due to #444
