### ISSUE TITLE
Develop changelog template for blogs

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#44]
Write changelog template for team to edit changelogs and post it in blogs. 
Place it in the knowledge.

**Comment by cyberadmin** [comment]
Looking for some forms of report visualization

**Comment by SaveTheAles** [comment]
@xhipster 
Add preliminary [changelog template](https://github.com/cybercongress/congress/blob/master/Organization/Changelog_template.md) at "organization" folder at congress repo

We can public changelogs at knowledge and vizualizate them with [progressbar](https://facelessuser.github.io/pymdown-extensions/extensions/progressbar/)

**Comment by xhipster** [comment]
Need significant improvements

**Comment by SaveTheAles** [comment]
Add changelog templates for blogs with pipeline and processes 
1st iteration
![image](https://user-images.githubusercontent.com/36516972/40363637-c6c0dbc2-5dd8-11e8-9b79-6d49956a8f46.png)
