### ISSUE TITLE
Make presentation about cybernode for developers in Kiev

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#47]

**Comment by 21xhipster** [comment]
@litvintech Please, post link here

**Comment by litvintech** [comment]
@21xhipster https://docs.google.com/presentation/d/1LfRzydv4TmVaD3V46mnA9izYQYaotb7lMg-iq2zDckE/edit?usp=sharing

**Comment by litvintech** [comment]
IPFS CID of presentation
QmPAz8iuoJWHr4jrvfXZ7pDycV1kPTyPVBrDWDj3353JAg
