### ISSUE TITLE
Create a landing page for chaingear project 

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#55]

**Comment by SaveTheAles** [comment]
@xhipster @litvintech 
For now chaingear landing page available on https://chaingear.netlify.com/
Powered by netlifi, hugo and introduction theme for hugo. 
Also we waiting for landing filling with "values", "roadmap" and pictures.

**Comment by xhipster** [comment]
Issue moved to [cybercongress/chaingear #977](https://github.com/cybercongress/chaingear/issues/977) via [**ZenHub**](https://www.zenhub.com/)
