### ISSUE TITLE
Setup gitcoin and prepare workflow to work with

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#6]

**Comment by abitrolly** [comment]
This work is still needs to be done.

Allocate funds on shared gitcoin.co address. Right now there is only mine with my own funds - 0x63b7608B7F47de1c0D1F94F85ffcb260Fbcb4890

So, for shared operations, this must be a contract with limited list of people to control it.

**Comment by hleb-albau** [comment]
@abitrolly Why it's closed?

**Comment by abitrolly** [comment]
Moved to `cyber-search`? https://github.com/cybercongress/cyber-search/issues/74

**Comment by 21xhipster** [comment]
It doesn't seems that a team has all necessary tooling installed

**Comment by litvintech** [comment]
@SaveTheAles made guide for gitcoin, prepared issue template, made meeting how to work with
all team members toke ethers for gitcoin's bounties
