### ISSUE TITLE
Add auto changelog generator to each project

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#66]
Use this [generator](https://github.com/github-changelog-generator/github-changelog-generator) and looking for opportunities to use it with .circleCI
- [x] cyber-search
- [ ] cyber-markets
- [ ] congress
- [ ] cyberd
- [ ] cyb
- [ ] cyb-js
- [ ] cybernode

**Comment by hleb-albau** [comment]
To enable changelog autogeneration for repo next should be done:
- [ ] [Generate access token for cyberadmin](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
- [ ] Add generate token as env **CHANGELOG_GITHUB_TOKEN** variable in Circle CI.
- [ ] [Generate new sha-rsa key](cybercongress/congress#66) for github(pub key) and circle ci(private key). 
- [ ] Remove old circle ci key from github repo. Add generated one (public part) with write permissions.
- [ ] Remove old circle ci key from circle ci **Checkout Keys** settings. Add generated one (private part) into **SSH Permissions** settings with host name **"github.com"**.
- [ ] [Add CircleCi job](https://github.com/cybercongress/cyber-search/pull/214/commits/15692dcb4d391e64763ac0cc6dd9d4ea786c1c36)  to your repo **.circleci/config.yml** file.

**Comment by hleb-albau** [comment]
![screenshot from 2018-06-14 14-49-26](https://user-images.githubusercontent.com/2991991/41410854-76f5d13e-6fe3-11e8-98b7-ba8dcade2185.png)
![screenshot from 2018-06-14 14-49-49](https://user-images.githubusercontent.com/2991991/41410856-7716b228-6fe3-11e8-9289-dcb9d32d7d7a.png)
![screenshot from 2018-06-14 14-50-03](https://user-images.githubusercontent.com/2991991/41410857-7734ac2e-6fe3-11e8-9c0a-d0a42a141e34.png)
![screenshot from 2018-06-14 14-50-31](https://user-images.githubusercontent.com/2991991/41410858-77544ca0-6fe3-11e8-9b3f-7dab9a108185.png)

**Comment by asadovka** [comment]
we need to change admin to cyberadmin42
