### ISSUE TITLE
Design approach for communication with communities

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#71]
- Github and Gitcoin
- Steem (profile and post)
- Medium (profile and post)
- Reddit (subreddit design)
- Telegram 
- Youtube 

@SaveTheAles - What else?

**Comment by SaveTheAles** [comment]
# For now we have:

### github and gitcoin

#### cyberd repo @hleb-albau @arturalbov 
- [x] CI
- [x] automatic collecting docs to wiki
- [x] relevant badges
- [ ] gitcoin badge
- [ ] Code of conduct
- [ ] Contributing
- [ ] PR template
- [x] issue template
- [ ] Changelog
- [x] Landing

Notes: links ti Github issue and contributing guide is not valid

#### cyb repo @asadovka @Pechalka @vstavetski 
- [x] CI
- [ ] automatic collecting docs to wiki
- [x] relevant badges
- [x] gitcoin badge
- [ ] Code of conduct
- [ ] Contributing
- [x] PR template
- [x] issue template
- [ ] Changelog
- [x] Landing

Notes: security alert is not ok, Roadmap link at readme reference to epic board.

#### chaingear repo @litvintech 

- [x] CI
- [ ] automatic collecting docs to wiki
- [x] relevant badges
- [x] gitcoin badge
- [ ] Code of conduct
- [x] Contributing
- [ ] PR template
- [x] issue template
- [ ] Changelog
- [x] Landing

#### congress repo @SaveTheAles @xhipster  
- [x] gitcoin badge
- [ ] Code of conduct
- [x] Contributing
- [x] PR template
- [x] issue template
- [x] Landing

It's enough to make our repos more charming

### Steemit

Steemit posting on a flow. Account is ready to. 

### Medium is die for us

### Reddit

Designed already

### Twitter

Designed already

### Telegram channel

Designed already

### Telegram dev chat

I would love to add github release notify bot

### YouTube 

cyber•Academia

@xhipster Well, what do you say?

**Comment by asadovka** [comment]
@SaveTheAles security vulnerability is fixed. to remove the badge we need to merge changes with master branch

**Comment by asadovka** [comment]
@SaveTheAles please, check also if master branch is protected in each repo
