### ISSUE TITLE
Setup DNS management for domains

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#8]

**Comment by 21xhipster** [comment]
All domains except *crowser* has been moved to [Google Cloud DNS](https://console.cloud.google.com/net-services/dns/zones?project=cybernode-196114). And issue is blocked by #[browser name](https://github.com/cybercongress/cyber-browser/issues/90) @asadovka @litvintech @hleb-albau

**Comment by xhipster** [comment]
Moved DNS management of `cyb.*` domains to Google Cloud
