### ISSUE TITLE
 Litvintech's wedding vacation proposal

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#97]
@xhipster @hleb-albau 
It's Saturday I'm getting married
I need a week+ for vacation - from 23 to 31 July
This is the proposal, and also the example of future discussions about vacations for team's members

**Comment by xhipster** [comment]
Congrats! Cannot predict anything blocking you from honeymoon :-)

**Comment by xhipster** [comment]
@asadovka I suggest to mark our calendar with all day events for vacations :-)
