### ISSUE TITLE
Asadovka vacation 1

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#98]
@xhipster @hleb-albau @litvintech 
I need a week for Druksiai festival (30.07 - 05.08)
There will be a very weak internet/cell network, but I'll have opportunity to communicate couple times in a week.

On Friday (03.08) I could not physically hold the demo & retrospective events, so I ask @litvintech to hold this instead of me.

@litvintech lets communicate, I will tell you how to collect metrics.

**Comment by xhipster** [comment]
Couple of days overlap with @litvintech honeymoon is ok? Please setup agreed events in calendar.
