### ISSUE TITLE
Asadovka vacation 2 

### ISSUE THREAD

**Issue by asadovka** [cybercongress/congress#99]
@xhipster @hleb-albau @litvintech
I need a week for Brigantina (20.08 - 27.08)
There will be a very weak internet/cell network, but I'll have opportunity to communicate couple times in a week.

As a pesponsible person for opening the sprints I'll attend office and hold planning on Monday (20.08).

**Comment by xhipster** [comment]
I think your org functions must be executable by any member of congress, so I would love to get masterclass in Iceland.

**Comment by asadovka** [comment]
@xhipster sure!

**Comment by hleb-albau** [comment]
I will collect metrics from last block sprint.
